import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import { LinkArrow } from "@/components/Icons";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import profilePic from "../../public/images/developer-pic-1.png";
import lightbulb from "../../public/images/svgs/lightbulb.svg";
import TransitionEffect from "@/components/TransitionEffect";
import Typewriter from "typewriter-effect";
export default function Home() {
  return (
    <>
      <Head>
        <title>Kaushtubh Agrawal | Home Page </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Kaushtubh"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
              />
            </div>
            <div className="w-1/2 flex flex-col items-center  lg:w-full lg:text-center ">
              <AnimatedText
                text="Hi I'm Kaushtubh Agrawal"
                className="!text-xl !text-left 2xl:!text-5xl xl:!text-4xl lg:!text-center lg:!text-4xl md:!text-3xl sm:text-2xl xs:!text-xl "
              />
              <div className="w-full mx-auto py-2 flex items-center justify-center text-center overflow-hidden  sm:py-0">
                <h1
                  className={` flex w-full text-dark font-bold capitalize  !text-5xl !text-left  2xl:!text-4xl xl:!text-3xl lg:!text-center lg:!text-4xl md:!text-4xl sm:!text-3xl xs:!text-2xl  dark:text-light`}
                >
                  <div className="flex lg:px-[30%] sm:px-[25%] xs:px-[20%]">
                 
                 <Typewriter
                    options={{
                      strings: ["Frontend Developer", "Open Source", "Freelancer"],
                      autoStart: true,
                      loop: true,
                      delay: 50,
                      cursor: `_`,
                      pauseFor: 100,
                      deleteSpeed: 50,
                    }}
                  />
                  </div>
                </h1>
              </div>

              <p className="my-4 text-base font-medium md:text-sm sm:text-xm ">
                As a skilled full-stack developer I am dedicated to building
                innovative solutions that deliver exceptional user experiences.
                With a deep understanding of the latest technologies and trends,
                I can help turn your ideas into high-quality, high-performance
                applications. Check out my portfolio and Posts to see some of my
                latest projects and insights into my development process.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Resume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light
                   hover:text-dark border-2 border-solid border-transparent
                    hover:border-dark 
                    dark:bg-light dark:text-dark
                    hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base "
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium capitalize tex-dark bg-light underline dark:text-light dark:bg-dark md:text-base  "
                  href="mailto:kaushtubhagrawal45@gmail.com"
                  target={"_blank"}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={lightbulb} alt="SourabhJo7" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
